import type { Metadata } from 'next'

/**
 * Application metadata configuration for Next.js.
 *
 * Defines default title, SEO tags, and author info.
 */
const siteMetadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export { siteMetadata }
